@startmindmap MindMaColors

title Mind Map With Colors

* Item
** Sub item
**[#lightgreen]:Multiline
sub item;
*** Sub sub item

left side

** left side sub item
**[#orange] Another left side sub item
*** left side sub sub item

' NOTES:
' - no space before :
@endmindmap
