@startuml SequenceDiagramWithArrows

title Sequence With Arrow Types

actor "Actor 1" as actor_1
participant "Participant 1" as participant_1
participant "Participant 2" as participant_2
participant "Participant 3" as participant_3
participant "Participant 4" as participant_4

activate actor_1
actor_1 --> participant_1 ++ : Start it off
deactivate actor_1
participant_1 ->> participant_2 ++ : Do 1st thing (async)
deactivate participant_1
participant_2 -->> participant_3 ++ : Do 2nd thing (async and dashed)
deactivate participant_2
participant_3 ->> participant_4 ++ : Ask for "something"
return Something
deactivate participant_3

' NOTES:
' - Async
' - Dashed
' - Return matches arrow head to origin call

@enduml
