@startuml ObjectStyles
!include common.puml

skinparam linetype ortho

skinparam object {
    FontName FONT_TEXT
    FontColor black
    AttributeFontName FONT_TEXT
    AttributeFontColor black
    BackgroundColor white
    BorderColor black
}
@enduml
