@startuml C4Context
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

System_Ext(external_system, "External System", "Description of that external system")

System(my_system, "My System", "Description of my system")
Rel(external_system, my_system, "These 2 systems are related!")

Person(a_person, "Person", "This is a person who uses my system")
Rel(a_person, my_system, "Interactions")

System_Ext(another_external_system, "Another External System")
Rel(my_system, another_external_system, "Fetch Content")

' NOTES:
' - https://c4model.com/
' - helps to understand interactions with external systems and users
' - My System might be many sub-systems, e.g. microservices, UIs, DBs, etc
' - includeurl - macros & styles
' - description not required

@enduml
